FROM golang:1.23 AS base
ARG VERSION
WORKDIR /issuer-node
ENV GOBIN=/issuer-node/bin
COPY ./api ./api
COPY ./cmd ./cmd
COPY ./tools/vault-migrator ./tools/vault-migrator
COPY ./internal ./internal
COPY ./pkg ./pkg
COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod tidy

