test:
  orgName: "org1"
  orgDomain: "org1.example.com"
  orgMSP: "Org1MSP"
  orgUsername: "User1"
  orgPeerEndpoint: "dns://localhost:7051"
  orgPeerName: "peer0"
  orgPeerHostAlias: "peer0.org1.example.com"
  orgCryptoPath: "/opt/organizations/peerOrganizations/org1.example.com"
  chainCode: "identity"
  channelID: "mychannel"
  networkFlag: 0b0101_0010
  chainID: 84001
  method: iden3